### ISSUE TITLE
Laravel integration

### ISSUE THREAD

**Issue by jjhesk** [amphp/websocket-client#10]
its a great library and this is the best one among other libs. Are there any plans to create a walk thru installations for laravel?

**Comment by kelunik** [comment]
What exactly are you looking for?

**Comment by jjhesk** [comment]
a manual to setup the demo app on laravel.  That would a great help if that is written in somewhere~

**Comment by kelunik** [comment]
Could you provide a link to the thing you're trying to setup? Do you mean https://laravel.com/docs/5.5/broadcasting? Which transport do you plan to use?

**Comment by kelunik** [comment]
Without further information I can't really help you. I'm therefore going to close this issue. If you respond with further information and more specific questions, we can always re-open it.
