### ISSUE TITLE
In Rfc6455Connection.php line 189:The connection was closed: Client closed the underlying TCP connection

### ISSUE THREAD

**Issue by pursonc** [amphp/websocket-client#13]
Could you give me some advise that how to fix this error 

In Rfc6455Connection.php line 189:The connection was closed: Client closed the underlying TCP connection

**Comment by kelunik** [comment]
It means the connection got closed without a closing handshake at the WebSocket protocol level. When does this happen? Immediately? After some time?

**Comment by pursonc** [comment]
@kelunik After some time . i connect to the server :  wss://real.okex.com:10440/websocket/okexapi

and the api document :https://github.com/okcoin-okex/API-docs-OKEx.com/blob/master/API-For-Futures-EN/WebSocket%20API%20for%20FUTURES.md

**Comment by kelunik** [comment]
Connection breaks might happen from time to time for various reasons. If the connection breaks, you have to create a new one.

**Comment by trowski** [comment]
Closing this issue due to being idle for some time. If you have additional questions feel free to reopen this issue or open a new issue.
