### ISSUE TITLE
RC is not compatible with amphp/http-server:^2

### ISSUE THREAD

**Issue by remorhaz** [amphp/websocket-client#22]
Thanks for your great job once again, guys! In my project I use both HTTP server and WebSocket client/server libraries, and the last amphp/http-server that is installable is RC2 because of league/uri version conflict. I hope there will be a compatible websocket libs release tagged soon.

P.S.: I use it in a semi-production environment and I'm ready to deal with RC risks, but I feel too dangerous to switch to dev-master, so I need at least RC.

**Comment by trowski** [comment]
Just tagged `v1.0.0-rc2`. Assuming there aren't any issues with this RC, I'll tag a final soon.

**Comment by remorhaz** [comment]
Upgraded my systems, everything runs perfect. Thank you!
