### ISSUE TITLE
Connect through proxy server

### ISSUE THREAD

**Issue by butschster** [amphp/websocket-client#24]
Hi!

How can I create connection with websocket server through proxy server?

**Comment by kelunik** [comment]
You can pass a custom `HttpClient` to [`Rfc6455Connector`](https://github.com/amphp/websocket-client/blob/e9187484af8f4c9ca31a4ebaa64dbe0776dd50de/src/Rfc6455Connector.php), so you can leverage the full proxy support that's available in `HttpClient`: [`socks4`](https://github.com/amphp/http-client/blob/f7f6dec1b2eabfc7023daedbbe479eead7731909/examples/proxy/socks4.php), [`socks5`](https://github.com/amphp/http-client/blob/f7f6dec1b2eabfc7023daedbbe479eead7731909/examples/proxy/socks5.php), and [`CONNECT` tunnels](https://github.com/amphp/http-tunnel).
