### ISSUE TITLE
how to end loop from outside ?

### ISSUE THREAD

**Issue by michabbb** [amphp/websocket-client#27]
hi there,

thanks for this great package!
i have a simple question: when the loop is running and the client is waiting for some data from the server:

```php
while ($message = yield $this->connection->receive()) {
.....
}
```

i can only do something (inside the while loop) when the server is sending something.
but lets say i want to send something to the server, even the server didn´t send anything,
how can i do this ? 

in my example i am catching `CTRL+C` to close the connection and end the loop. but for now, my code
only gets executes whenever the server is sending something, but not just-in-time. 

what i am doing:

```php
pcntl_async_signals(true);
pcntl_signal(SIGINT, [$this, 'shutdown']);
pcntl_signal(SIGTERM, [$this, 'shutdown']);
```

and my shutdown function is only setting `$this->stop = true` and inside the while, i am sending something to the server, close the connection and `Loop::stop`. but all this only happens, if the server is sending something, i cannot run all that without any feedback from the server.

thanks for any help!

**Comment by kelunik** [comment]
Don't use manual calls to pcntl_signal, use Loop::onSignal instead.

You can use call / asyncCall to do things concurrently.

**Comment by michabbb** [comment]
works like a charm, thanks a lot ! 👍
