### ISSUE TITLE
Invalid Websocket URI provided

### ISSUE THREAD

**Issue by curtiscarlson** [amphp/websocket-client#32]
I am getting the error "Invalid Websocket URI provided".  

I am fairly certain the websocket URI is just fine, as it works in javascript.  

js:
```var mySock = new WebSocket("wss://" + streamerSocketUrl + "/ws"); ```

php:
```
\Amp\Loop::run(function () {
        /** @var Client\Connection $connection */
          $connection = yield Client\connect("wss://" . $streamerSocketUrl . "/ws");
``` 

I have echo'd it out so I know it is not a problem with the uri, it is something else.  anything I could be missing??

**Comment by kelunik** [comment]
What's the stack trace of the error?

**Comment by curtiscarlson** [comment]
I don't know.  I am running on command line and that is all I'm getting...  do you know how I could catch the error and get the trace?  Here is what I tried: 

```
try {
        $connection = yield connect("wss://" . $userPrincipalsResponse->streamerInfo->streamerSocketUrl . "/ws");
        }
        catch (\Exception $e) {
          print_r($e->getTrace());
        }
```

**Comment by curtiscarlson** [comment]
Hello and thank you for the prompt response!  I did not realize the error was being written to my log.  I was able to diagnose it as a context error of the Amp function.  In my example above I needed to add use ($streamerSocketUrl).  That got it to connect to the server but now I have a different error: 

```
inet_pton(): Unrecognized address streamer-ws.tdameritrade.com : C:\\...\\vendor\\amphp\\socket\\src\\DnsConnector.php line: 40"
``` 
which is quickly followed by 
``` 
fclose(): supplied resource is not a valid stream resource : C:\\...\\vendor\\amphp\\process\\lib\\Internal\\Windows\\SocketConnector.php line: 313
``` 

the address streamer-ws.tdameritrade.com is the same address being passed in the variable that works just fine in javascript, so it is still the same isssue although for a different reason.  It initially connects to the server but then when I try to send the first message (to subscribe to data) this is the error that comes back.  the code looks like this: 

```
// Connects to the Kaazing echoing websocket demo.
      \Amp\Loop::run(function () use ($url, $request) {

          /** @var Client\Connection $connection */
          $connection = yield Client\connect($url);

          echo "sending request" . PHP_EOL;
          yield $connection->send(json_encode($request));

          while ($message = yield $connection->receive()) {
              /** @var Message $message */
              $payload = yield $message->buffer();
              printf("Received: %s\n", $payload);
          }
      });
```

in js it looks something like this: 
```

      var mySock = new WebSocket("wss://" + userPrincipalsResponse.streamerInfo.streamerSocketUrl + "/ws");

      mySock.onmessage = function(evt) {
        console.log(evt.data);
      };

      mySock.onclose = function() {
        console.log("CLOSED");
      };
    mySock.waitForConnection = function (callback, interval) {
        if (mySock.readyState === 1) {
            callback();
        } else {

            // optional: implement backoff for interval here
            setTimeout(function () {
                mySock.waitForConnection(callback, interval);
            }, interval);
        }
      };

      mySock.waitForConnection(function(){
        mySock.send(JSON.stringify(request))
      },100);
``` 

I noticed that I left a small timeout there when I implemented in javascript, maybe something like that is needed here?  not really sure...I wrote the js like a year ago

**Comment by kelunik** [comment]
The follow-up error is likely to an error handler that ignores error suppression. Try adding the following at the top of your error handler:

```php
if (!(error_reporting() & $code)) {
    return false;
}
```

**Comment by curtiscarlson** [comment]
Hello, I am not sure if you responded before I updated my post or not, but your answer does not make sense to me...I am thinking I must have ninja updated it...can you please take a look?  I am using monolog for error handling.

**Comment by kelunik** [comment]
If responded afterwards as it seems. Do you use `set_error_handler` somewhere or does `monolog` register that?

**Comment by curtiscarlson** [comment]
I found a spot where I can add in that code.  I really don't understand it or how it works but now I get the same outcome but without the error.  I just get nothing after the request is sent and the program stops running.  I suppose it is possible my request is somehow incorrect, but I am not getting back any server response to be able to know.

**Comment by kelunik** [comment]
You mean without the first error? Please try updating `amphp/process` to `v1.1.1` which I just relased.

**Comment by curtiscarlson** [comment]
updated to v1.1.1, no change.

**Comment by curtiscarlson** [comment]
By the way my output to the script above looks like this: 
``` 
setting up....
fetching websocket connection: wss://streamer-ws.tdameritrade.com/ws
sending request

c:\>
```

**Comment by kelunik** [comment]
Do you control the server side and can you debug it?

**Comment by curtiscarlson** [comment]
I don't.  Its run by td ameritrade.  There is no support.  But this works perfectly in javascript so I know it works.  I connected just fine yesterday.  The code is basically the same, I posted both versions...  Their system works by connecting, then sending a request for subscription to a stream.  It is possible my request is off, but since I am not getting a response or an error...I have nothing to work with here.  I still think it has to do with "Unrecognized address streamer-ws.tdameritrade.com".  Is there  any way to get a more verbose output?

**Comment by trowski** [comment]
You're still seeing `fclose(): supplied resource is not a valid stream resource` even after updating to v1.1.1 of amphp/process?

**Comment by curtiscarlson** [comment]
No, that one is gone.  But I am still getting: 
```{"message":"inet_pton(): Unrecognized address streamer-ws.tdameritrade.com : C:\\...\\vendor\\amphp\\socket\\src\\DnsConnector.php line: 40","context":[],"level":300,"level_name":"WARNING","channel":"Slim Project Console","datetime":{"date":"2021-03-30 20:10:13.286122","timezone_type":3,"timezone":"America/New_York"},"extra":[],"id":"onzcqz2tn0j8"}```

**Comment by curtiscarlson** [comment]
Yo!  I got this working!  It was indeed something wrong with my request, I just had to iron out a few differences between js and php.  Thank you very much for your help.  I think that the error thrown was due to TDA closing the connection, and the error message it was giving me was throwing me off.  I hope it helps you with your development.

**Comment by programmin1** [comment]
> I don't. Its run by td ameritrade. There is no support. 

Sure there is. Client Services -> Message Center on their main page is one way to send them message.

I'm curious what api is this, what is it for? Sounds interesting.

**Comment by curtiscarlson** [comment]
Ok there is relatively no support...they take weeks to get back to you.  The support here is much better :).  The websocket provides streaming market data for stocks and futures.

**Comment by programmin1** [comment]
Where is that, can you link an example code?

**Comment by curtiscarlson** [comment]
https://developer.tdameritrade.com/content/streaming-data
