### ISSUE TITLE
Missing `$closeTimeout` property

### ISSUE THREAD

**Issue by lt** [amphp/websocket-client#4]
Not sure if the socket is being closed from the remote end, or the local end due to a timeout, but getting the following notice spam.

```
Notice: Undefined property: Amp\Websocket\Rfc6455Endpoint::$closeTimeout in vendor/amphp/websocket/lib/Rfc6455Endpoint.php on line 428
```

**Comment by staabm** [comment]
@bwoebi I guess we should assign `null` instead of `unset` the closeTimeout

**Comment by bwoebi** [comment]
Urgs, I always forget that unset() actually removes them :x … Will fix.
