### ISSUE TITLE
WebsocketHandshake does not support cloning

### ISSUE THREAD

**Issue by leonardocustodio** [amphp/websocket-client#45]
Hello, since the last commit, I've not been able to use parallel + websocket-client.
I get the error:
```
Error thrown in context with message "Amp\Websocket\Client\WebsocketHandshake does not support cloning" and code "0" in /home/custodio/Development/Enjin/open-platform-core/vendor/amphp/amp/src/ForbidCloning.php:9; call Amp\Parallel\Context\ContextPanicError::getOriginalTrace() for the stack trace in the context as an array; if the Xdebug extension is enabled, set "xdebug.mode" to "debug" to include the exception stack trace in the context in the exception message
```

I've updated all dependencies to the last amphp commit on every package still no luck. Is there something else that we should do or should we just wait for future releases?

**Comment by trowski** [comment]
Oops, I went too far with copy/paste and didn't notice because apparently we have really poor test coverage (i.e., none) on that class.

Fixed in https://github.com/amphp/websocket-client/commit/89f6a4a15903ebcebaefc7e45ec9d99925a31479.

**Comment by leonardocustodio** [comment]
Awesome, working fine now, thanks mate ;D
