### ISSUE TITLE
Release based on Amp v2

### ISSUE THREAD

**Issue by shtse8** [amphp/websocket-client#6]
it seems amphp is updated to v2. but composer still requiring v1.

**Comment by kelunik** [comment]
You're right, this repository has seen very little love. The v1 release also isn't that old. There aren't any tests right now, so I can't even tell whether the migration to v2 is complete in the `master` branch, but I think it is. I'm pinging @trowski and @bwoebi here.

Maybe you could try it with `dev-master#6f846aec74a167cfbffc483f093ee45c23ebd40d` and report back whether there are any issues? I think we can totally release a `v0.2.0` and leave #5 for later consideration.

**Comment by shtse8** [comment]
Yes, I agree with you. It's better to release Amp v2 first for basis usage. I will try the dev-master and see if it has any problem.

**Comment by kelunik** [comment]
There'll be a release later today or tomorrow.
