### ISSUE TITLE
Integrate connect and TLS context into Options

### ISSUE THREAD

**Issue by kelunik** [amphp/websocket-client#9]
This was an oversight and currently you have to pass `null, null, $options` if you don't want to modify these.

**Comment by trowski** [comment]
This has been implemented in a much better way in master, integrating `Options` into `Handshake`. The connect context is now the second argument to `connect()`, e.g.: `connect($handshake, $context)`.

**Comment by StormCh** [comment]
Hi, `connect()` excepts only cancellation as second parameter. How to use websocket-client to connect to a TLS Socket like wss://example.com? The documentation is not really helpful if you want to connect with *.crt and *.key file.
